### ISSUE TITLE
Doesn't compiles: error casting ulong to uint

### ISSUE THREAD

**Issue by volt0** [nomad-software/dunit#4]
I trying to compile with dmd v2.063.2, dub v0.9.18 on windows7 32-bit
Output:

```
D:\1310\mtk> dub --build=unittest
Checking dependencies in 'D:\1310\mtk'
The following changes will be performed:
Install dunit >=1.0.0, userWide
Downloading dunit 1.0.0...
Installing dunit 1.0.0 to C:\Users\volt\AppData\Roaming\dub\packages\...
dunit has been installed with version 1.0.0
Building configuration "application", build type unittest
Running dmd (compile)...
C:\...\dunit-1.0.0\source\dunit\toolkit.d(41): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(41): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\error.d(108): Error: template instance dunit.toolkit.assertEqual!(string, string) error instantiating C:\Users\volt\AppData\Roaming\dub\packages\dunit-1.0.0\source\dunit\toolkit.d(41): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(41): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\error.d(110): Error: template instance dunit.toolkit.assertEqual!(uint, int) error instantiating
C:\...\dunit-1.0.0\source\dunit\toolkit.d(41): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(41): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\error.d(111): Error: template instance dunit.toolkit.assertEqual!(string[], string[]) error instantiating
C:\...\dunit-1.0.0\source\dunit\toolkit.d(207): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(207): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\result.d(76): Error: template instance dunit.toolkit.assertEmpty!(DUnitAssertError[string]) error instantiating
C:\...\dunit-1.0.0\source\dunit\toolkit.d(387): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(387): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\toolkit.d(316): Error: template instance dunit.toolkit.assertType!(bool, bool) error instantiating
C:\...\dunit-1.0.0\source\dunit\result.d(79):        instantiated from here: assertTrue!(bool)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(320): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(320): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\result.d(79): Error: template instance dunit.toolkit.assertTrue!(bool) error instantiating
C:\...\dunit-1.0.0\source\dunit\toolkit.d(250): Error: constructor dunit.error.DUnitAssertError.this (string message, string file, uint line) is not callable using argument types (string, string, ulong)
C:\...\dunit-1.0.0\source\dunit\toolkit.d(250): Error: no constructor for DUnitAssertError
C:\...\dunit-1.0.0\source\dunit\result.d(82): Error: template instance dunit.toolkit.assertFalse!(bool) error instantiating
Error: Build command failed with exit code 1
```

For versions "1.0.0-beta" and "~master" output is same.
